{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "완료된 배치",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monew_batch_job_success_total{exported_job=\"newsCollectJob\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "관심사",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monew_interest", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "수집된 기사",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monew_article", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "관심사별 기사 개수",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "monew_interest_article_mapped_total",
     "legendFormat": "{{interestName}}"
    }
   ]
  },
  {
   "title": "배치 작업 소요 시간",
   "type": "stat",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monew_batch_job_duration_seconds_sum{exported_job=\"newsCollectJob\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "회원수",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monew_user", "legendFormat": "__auto" }
   ]
  }
 ]
}