coverage:
  status:
    project:
      default:
    patch:
      default:

comment: true

ignore:
  - "**/seeder/**"
  - "**/config/**"
  - "**/*ActivityEventListener.java"
  - "**/Q*.java"
  - "**/util/**"