coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        branches: off
    patch:
      default:
        branches: off

comment: true

ignore:
  - "**/seeder/**"
  - "**/config/**"
  - "**/*ActivityEventListener.java"
  - "**/Q*.java"