coverage:
  status:
    project:
      default:
    patch:
      default:

ignore:
  - "**/*Application.java"
  - "**/*Config.java"
  - "**/dto/**"
  - "**/entity/**"
  - "**/exception/**"
  - "**/logging/**"
  - "**/mapper/**"
  - "**/util/**"

comment: false