services:
  # PostgreSQL 데이터베이스 서비스
  postgres:
    image: postgres:15-alpine
    container_name: monew-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_EXTERNAL_PORT:-5433}:${POSTGRES_PORT:-5432}"
    volumes:
      # 실행 sql은 라인이 아닌 알파벳 순서로 실행되기 때문에 번호 명시
      - monew_postgres:/var/lib/postgresql/data
      - ./src/main/resources/docker-pg-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
    networks:
      - monew-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB 데이터베이스 서비스
  mongo:
    image: mongo:latest
    container_name: monew-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGO_EXTERNAL_PORT:-28017}:${MONGO_PORT:-27017}"
    volumes:
      - monew_mongo:/data/db
      - ./src/main/resources/docker-mongo-init.js:/docker-entrypoint-initdb.d/docker-mongo-init.js
    networks:
      - monew-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/monew_mongo --quiet
      interval: 20s  # healthcheck 대기 시간을 20초로 설정
      timeout: 10s
      retries: 10

  # 애플리케이션 서비스
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: monew:monew-local
    container_name: monew-app
    environment:
      SPRING_PROFILES_ACTIVE: postgres # 컨테이너 환경용
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_HOST: ${MONGO_HOST} # 몽고 DB
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      SERVER_PORT: ${APP_INTERNAL_PORT:-80}
      JVM_OPTS: ${JVM_OPTS:-}
      # AWS S3 Configuration
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      # NAVER
      NEWS_API_NAVER_CLIENT_ID: ${NEWS_API_NAVER_CLIENT_ID}
      NEWS_API_NAVER_CLIENT_SECRET: ${NEWS_API_NAVER_CLIENT_SECRET}
      # NAVER API
      NEWS_API_NAVER_BASE_URL: ${NEWS_API_NAVER_BASE_URL}
      # RSS URLs
      NEWS_RSS_HANKYUNG_URL: ${NEWS_RSS_HANKYUNG_URL}
      NEWS_RSS_CHOSUN_URL: ${NEWS_RSS_CHOSUN_URL}
      NEWS_RSS_YONHAP_URL: ${NEWS_RSS_YONHAP_URL}
    ports:
      - "${APP_EXTERNAL_PORT:-8080}:${APP_INTERNAL_PORT:-80}" # 외부 포트와 내부 포트 매핑
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - monew-network
    restart: unless-stopped

  # Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: monew-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - app
    networks:
      - monew-network
  # Metrics GUI
  grafana:
    image: grafana/grafana:latest
    container_name: monew-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'password'
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    networks:
      - monew-network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana

# 볼륨 정의
volumes:
  monew_postgres:
    driver: local
  monew_mongo:
    driver: local

# 네트워크 정의
networks:
  monew-network:
    driver: bridge
