spring:
  application:
    name: sb03-monew-team1

  devtools:
    restart:
      enabled: false

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB # 한 번에 최대 업로드 가능 용량

  datasource:
  # 환경별로 오버라이드
  # url: jdbc:postgresql://localhost:5432/db_name
  # username: ${USER_NAME}
  # password: ${USER_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: false
        show_sql: false

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

server:
  forward-headers-strategy: native

logging:
  level:
    root: info
    com.sprint.mission: info

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers  # 엔드포인트 노출
      base-path: /actuator  # Actuator 엔드포인트 기본 경로
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always      # 건강 상태 상세 정보 표시
      show-components: always   # 컴포넌트별 상태 정보 표시

news:
  api:
    naver:
      base-url: ${NEWS_API_NAVER_BASE_URL}
      client-id: ${NEWS_API_NAVER_CLIENT_ID}
      client-secret: ${NEWS_API_NAVER_CLIENT_SECRET}
    hankyung:
      url: ${NEWS_RSS_HANKYUNG_URL}
    chosun:
      url: ${NEWS_RSS_CHOSUN_URL}
    yonhap:
      url: ${NEWS_RSS_YONHAP_URL}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    backup-prefix: articles    # 기사 S3 저장 경로
    logDir: /app/logs    # 로그 경로
    log-prefix: logs    # 로그 S3 저장 경로

