spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: monew
    show-sql: true
    # OSIV 비활성화
    open-in-view: false

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    root: info
    com.sprint.mission: debug
